### ISSUE TITLE
Mong các bạn góp ý giúp mình!

### ISSUE THREAD

**Issue by jekkyboy** [jekkyboy/LT-KHDL#1]

**Comment by Tuyetmayy2410** [comment]
Chào bạn, mình là Tuyết là người có nhiệm vụ nhận xét cũng như đóng góp đồ án của bạn theo phân công của Thầy Kiên:
Đầu tiên, mình sẽ nhận xét trước nha: Mình thấy chủ đề đồ án của bạn khá hay, thú vị, nhất là đối với những tín đồ thích xem Anime như mình, còn về phần trình bày thì mình thấy bạn trình bày có thứ tự, logic, giúp người xem dễ hiểu, đáp ứng đầy đủ các yêu cầu của Thầy đặt ra. 
Kế tiếp là phần đóng góp ý kiến của mình: 
Về hình thức thì mình nghĩ bạn nên thêm vào tiêu đề đồ án để người xem có thể nhìn vào là thấy bạn muốn phân tích gì, bạn cũng có thể thêm phần lý do chọn đề tài đó để mọi người có thể hiểu rõ hơn về cái bạn đang phân tích cũng như là phần kết luận sau khi đã trả lời câu hỏi để người xem có thể biết được là sau quá trình phân tích tập dữ liệu đó thì sẽ rút ra điều gì ?
Về nội dung thì mình thấy bạn làm khá tốt, chỉnh chu, nhưng có một điều mình thắc mắc là trong quá trình khám phá dữ liệu đến phần số lượng các cột có giá trị thiếu (hoặc '-') thì hầu như là các cột đều bị thiếu, có cột thiếu lên đến 742, trong khi dữ liệu của bạn chỉ có 1563 dòng  thôi nhưng đến phần tiền xử lý thì mình lại không thấy bạn thực hiện các bước xử lý có liên quan đến các giá trị bị thiếu này, mình thắc mắc rằng liệu giá trị bị thiếu nhiều như vậy có ảnh hưởng gì đến kết quả bạn đã phân tích hay không ?Hoặc là bạn nghĩ bạn có sai lầm trong viêc chọn tập dữ liệu không ?
Trên đây là những nhận xét và góp ý của cá nhân mình. Cám ơn bạn đã đọc

**Comment by jekkyboy** [comment]
Cảm ơn bạn, mình sẽ bỏ những cột thiếu nhiều dữ liệu đi. Không ảnh hưởng j đến kết quả phân tích hết vì mình không dùng nó, nhưng nói chung là dữ liệu mình chọn ko đủ tốt =)))
